alias dash='function dash () { docker exec -it "$@" sh; }; dash'
alias dbuild='docker compose up --force-recreate --build --remove-orphans'
alias dimgs='function dimgs () { docker images "$@"; }; dimgs'
alias dins='function dins () { docker network inspect "$@"; }; dins'
alias dlogs='function dlogs () { docker logs "$@"; }; dlogs'
alias dnet='docker network ls'
alias dps='docker ps -a'
alias drh='function drh () { docker run -it "$@" bash; }; drh'
alias drem='function drem () { docker image rm "$@" -f; }; drem'
alias drun='function drun () { docker run --rm -it -d "$@"; }; drun'
alias dsh='function dshf () { docker exec -it "$@" bash; }; dshf'
alias dstop='function dstop () { for i in $(docker ps -q); do docker stop $i; done }; dstop'
alias dvrun='function dvrun () { docker run --rm -it -v "$@"; }; dvrun'
alias dprune='docker system prune --volumes -a -f'
alias duprune='function duprune () { for i in $(docker images -f "dangling="true" -q --no-trunc); do docker rmi $i; done }; duprune'
alias dpruneall='docker system prune -a -f --volumes'